name: Build Telegram APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Modify Audio Code
        run: |
          # உங்கள் ஆடியோ பிளானுக்கான துல்லியமான பாத் (Updated for DrKLO)
          sed -i 's/AudioSource.MIC/AudioSource.VOICE_COMMUNICATION/g' Telegram/src/main/java/org/telegram/messenger/MediaController.java
          sed -i 's/noiseSuppression = true/noiseSuppression = false/g' Telegram/src/main/java/org/telegram/messenger/MediaController.java
          sed -i 's/echoCancellation = true/echoCancellation = false/g' Telegram/src/main/java/org/telegram/messenger/MediaController.java

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug -PgenerateUniversalApk=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-Universal-Internal-Audio
          # DrKLO ரிப்போசிட்டரியில் APK இங்கே தான் இருக்கும்
          path: "Telegram/build/outputs/apk/afat/debug/*universal.apk"
          
